-- CREATE DATABASE STUDENT RECORD KEEPING SYSTEM DATABASE PROJECT
-- CREATE 

DROP TABLE IF Exists Student
CREATE TABLE	Student
(
	StudentID		VARCHAR(5)		NOT NULL	CONSTRAINT StudentID PRIMARY KEY,
	FirstName		VARCHAR(20)		NULL,
	LastName		VARCHAR(30)		NULL,
	PhoneNo			TINYINT			NULL,
	Email			VARCHAR(50)		NULL,
	StreetNo		TINYINT			NULL,
	StreetName		VARCHAR(30)		NULL,
	City			VARCHAR(30)		NULL,
	Province		VARCHAR(30)		NULL,
	PostalCode		VARCHAR(6)		NULL
);
GO
SELECT * FROM	Student

DROP TABLE IF Exists Grades
CREATE TABLE	Grades
(
	CourseID		VARCHAR(20)		NOT NULL	CONSTRAINT CourseID PRIMARY KEY,
	Attendance		DECIMAL(3,2)	NULL,
	Quizes			DECIMAL(3,2)	NULL,
	Project			DECIMAL(3,2)	NULL,
	FinalExam		DECIMAL(3,2)	NULL
);
GO
SELECT * FROM	Grades

DROP TABLE IF Exists Finance
CREATE TABLE	Finance
(
	PaymentType		VARCHAR(15)		NOT NULL	CONSTRAINT PaymentType PRIMARY KEY,
	Tuition			DECIMAL(5,2)	NULL,
	LateFees		DECIMAL(5,2)	NULL,
	Sales			DECIMAL(4,2)	NULL,
	Scholarship		DECIMAL(5,2)	NULL
);
GO
SELECT * FROM	Finance

DROP TABLE IF Exists Course 
CREATE TABLE	Course
(
	Course2ID		VARCHAR(20)		NOT NULL	CONSTRAINT Course2ID	PRIMARY KEY,
	CourseName		VARCHAR(50)		NULL,
	Tuition			DECIMAL (3,2)	NULL,
	Length			TINYINT			NULL,
	Coop			BIT				NULL
);
GO
SELECT * FROM	Course

DROP TABLE IF Exists School
CREATE TABLE	School
(
	SchoolName		VARCHAR(20)		NOT NULL	CONSTRAINT SchoolName PRIMARY KEY,
	PhoneNo			TINYINT			NULL,
	Dli				VARCHAR(15)		NULL,
	StreetNo		TINYINT			NULL,
	StreetName		VARCHAR(30)		NULL,
	City			VARCHAR(30)		NULL,
	Province		VARCHAR(2)		NULL,
	PostalCode		VARCHAR(6)		NULL
);
GO
SELECT * FROM	Course

DROP TABLE IF Exists Instructor
CREATE TABLE Instructor
(
	InstructorID	VARCHAR(5)		NOT NULL	CONSTRAINT InstructorID PRIMARY KEY,
	FirstName		VARCHAR(20)		NULL,
	LastName		VARCHAR(30)		NULL,
	Specialization	VARCHAR(50)		NULL
);
GO
SELECT * FROM	Instructor