-- CREATE DATABASE STUDENT RECORD KEEPING SYSTEM DATABASE PROJECT
-- CREATE 

CREATE TABLE	Student
(
	StudentID	VARCHAR(5)		NOT NULL	CONSTRAINT PKWidget PRIMARY KEY,
	FirstName	VARCHAR(20)		NULL,
	LastName	VARCHAR(30)		NULL,
	PhoneNo		TINYINT			NULL,
	Email		VARCHAR(50)		NULL,
	StreetNo	TINYINT			NULL,
	StreetName	VARCHAR(30)		NULL,
	City		VARCHAR(30)		NULL,
	Province	VARCHAR(30)		NULL,
	PostalCode	VARCHAR(6)		NULL
);
GO
SELECT * FROM	Student

CREATE TABLE	Grades
(
	StudentID	VARCHAR(5)		NOT NULL	CONSTRAINT PKWidget PRIMARY KEY,
	CourseID	VARCHAR(20)		NOT NULL	CONSTRAINT PKWidget PRIMARY KEY,
	Attendance	DECIMAL(3,2)	NULL,
	Quizes		DECIMAL(3,2)	NULL,
	Project		DECIMAL(3,2)	NULL,
	FinalExam	DECIMAL(3,2)	NULL
);
GO
SELECT * FROM	Grades

CREATE TABLE	Finance
(
	PaymentType	VARCHAR(15)		NOT NULL	CONSTRAINT PKWidget PRIMARY KEY,
	Tuition		DECIMAL(5,2)	NULL,
	LateFees	DECIMAL(5,2)	NULL,
	Sales		DECIMAL(4,2)	NULL,
	Scholarship	DECIMAL(5,2)	NULL
);
GO
SELECT * FROM	Finance